### ISSUE TITLE
Showing error

### ISSUE THREAD

**Issue by arittASinha** [AeroAndZero/cry-or-not#1]
Sir,
I am not able to run the program. It is showing an error. What is the step by step procedures to run the program properly??

**Comment by AeroAndZero** [comment]
1. Make sure you have all the modules installed on your computer with Tensorflow gpu support and CUDA
2. Use python 3

After that, these are the steps to execute the software :
1. run mainGUI.py. reply to this issue if you get error. also list the error details
2. after mainGUI opens, select any .mp4 file you want to test this model on and it should work as expected

**Comment by AeroAndZero** [comment]
No further reply from you. Marking this issue as close.
